// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo_bMu08saAQs_HCtb95GJb7ZA_fr2c1I',
    appId: '1:922577745755:web:95b30e4d41d1a53bc28c7e',
    messagingSenderId: '922577745755',
    projectId: 'indian-political-analysis',
    authDomain: 'indian-political-analysis.firebaseapp.com',
    storageBucket: 'indian-political-analysis.appspot.com',
    measurementId: 'G-VY587CE5SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwIrFC4frY6IyQWqNvTTlkjBlkPKLfQ7o',
    appId: '1:922577745755:android:3ca31403c2773d01c28c7e',
    messagingSenderId: '922577745755',
    projectId: 'indian-political-analysis',
    storageBucket: 'indian-political-analysis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk361uYeczX1h_9c7t3Bbh0NhSRmB4wDg',
    appId: '1:922577745755:ios:ea7df8e9b832961bc28c7e',
    messagingSenderId: '922577745755',
    projectId: 'indian-political-analysis',
    storageBucket: 'indian-political-analysis.appspot.com',
    iosBundleId: 'com.alwaysbecreative.bpl.bhartPoliticalReports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk361uYeczX1h_9c7t3Bbh0NhSRmB4wDg',
    appId: '1:922577745755:ios:db781d6ef0424533c28c7e',
    messagingSenderId: '922577745755',
    projectId: 'indian-political-analysis',
    storageBucket: 'indian-political-analysis.appspot.com',
    iosBundleId: 'com.alwaysbecreative.bpl.bhartPoliticalReports.RunnerTests',
  );
}
